project:
  type: book
  render: 
    - "*.qmd"
    - "!*.md"
resources:
  - CNAME
book:
  title: "NHSR-way"
  author: "NHS-R Community"
  date: last-modified
  chapters:
    - index.qmd
    - code-of-conduct.qmd
    - style-guides.qmd
    - community-handbook.qmd
    - training.qmd
    - references.qmd
  page-footer:
    left: |
      NHS-R Way by the NHS-R Community
      
      NHS-R Community makes all of their materials publicly available under open source licenses
    right: |
      This unofficial book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-url: https://github.com/nhs-r-community/NHSR-way/
  repo-branch: main
  repo-actions: [edit, issue]
  site-url: https://nhsrway.nhsrcommunity.com/


bibliography: references.bib

format:
  html:
    theme: cosmo
